/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencv_samples_fd_DetectionBasedTracker */

#ifndef _Included_edu_cvc_uab_fd_DetectionBasedTracker
#define _Included_edu_cvc_uab_fd_DetectionBasedTracker
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_edu_cvc_uab_imagedetect_ImageExtractor_nativeDetect
(JNIEnv * jenv, jclass, jlong image, jdouble threshold, jdouble threshold_votes,
		jint num_min_features, jint num_targets, jstring path_model);


JNIEXPORT int JNICALL Java_edu_cvc_uab_imagedetect_ImageExtractor_nativeBuildDatabase
(JNIEnv * jenv, jclass, jint num_min_features, jint num_targets, jstring path_model, jstring path_files);

#ifdef __cplusplus
}
#endif
#endif
